/*
 *  Licensed to GraphHopper GmbH under one or more contributor
 *  license agreements. See the NOTICE file distributed with this work for
 *  additional information regarding copyright ownership.
 *
 *  GraphHopper GmbH licenses this file to you under the Apache License,
 *  Version 2.0 (the "License"); you may not use this file except in
 *  compliance with the License. You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.graphhopper.reader.dem;

import com.graphhopper.storage.DataAccess;

import javax.imageio.ImageIO;
import javax.imageio.ImageReadParam;
import javax.imageio.ImageReader;
import javax.imageio.stream.ImageInputStream;
import java.awt.Rectangle;
import java.awt.image.Raster;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;

/**
 * Reads the one-degree Cloud Optimized GeoTIFFs generated by Bikemap's
 * {@code elevation_worker/commands/compute_continuous_tiles.py}.
 * <p>
 * The dataset uses lowercase SRTM-style names such as {@code n46e010.tif}, but unlike a regular
 * SRTM provider its tiles contain Float32 samples and can have different resolutions. The first
 * access to a tile converts its actual raster dimensions and values into GraphHopper's short-based
 * {@link DataAccess} format. The converted data is then memory-mapped by default.
 * <p>
 * The cache directory must be the dataset's {@code continuous} directory and must be writable,
 * because the GraphHopper sidecar caches are stored next to the source COGs.
 */
public class BikemapElevationProvider extends TileBasedElevationProvider {
    static final int MIN_LATITUDE = -60;
    static final int MAX_LATITUDE = 84;
    static final int MIN_LONGITUDE = -180;
    static final int MAX_LONGITUDE = 180;

    private static final int CACHE_FORMAT_VERSION = 1;
    private static final int CACHE_VERSION_HEADER = 4;
    private static final int WIDTH_HEADER = 8;
    private static final int HEIGHT_HEADER = 12;
    private static final int SOURCE_MODIFIED_HEADER = 16;
    private static final int SOURCE_LENGTH_HEADER = 24;
    private static final double PRECISION = 1e7;
    private static final int DEGREE = 1;
    private static final double MIN_ELEVATION = -1_000;
    private static final double MAX_ELEVATION = 12_000;
    private static final int RASTER_CHUNK_HEIGHT = 512;
    private static final String TWELVE_MONKEYS_READER_PREFIX = "com.twelvemonkeys.";

    private final Map<String, HeightTile> cacheData = new HashMap<>();
    private final Set<String> missingTiles = new HashSet<>();

    public BikemapElevationProvider() {
        this("");
    }

    public BikemapElevationProvider(String cacheDir) {
        super(cacheDir.isEmpty() ? "/tmp/bikemap" : cacheDir);
        baseUrl = getCacheDir().getAbsolutePath();
    }

    @Override
    public double getEle(double lat, double lon) {
        String fileName = getFileName(lat, lon);
        if (fileName == null)
            return 0;

        HeightTile tile;
        synchronized (cacheData) {
            tile = cacheData.get(fileName);
            if (tile == null) {
                if (missingTiles.contains(fileName))
                    return 0;

                File source = new File(getCacheDir(), fileName);
                if (!source.isFile()) {
                    missingTiles.add(fileName);
                    return 0;
                }

                tile = loadTile(source, getMinLatitude(lat), getMinLongitude(lon));
                cacheData.put(fileName, tile);
            }
        }
        return tile.getHeight(lat, lon);
    }

    private HeightTile loadTile(File source, int minLat, int minLon) {
        String cacheName = "bikemap_" + source.getName().substring(0, source.getName().length() - 4) + ".gh";
        DataAccess heights = getDirectory().create(cacheName);
        boolean loadExisting = false;
        try {
            loadExisting = heights.loadExisting();
        } catch (Exception ex) {
            logger.warn("Cannot load {}, rebuilding it: {}", cacheName, ex.getMessage());
        }

        if (loadExisting && !matchesSource(heights, source)) {
            getDirectory().remove(cacheName);
            heights = getDirectory().create(cacheName);
            loadExisting = false;
        }

        int width;
        int height;
        if (loadExisting) {
            width = heights.getHeader(WIDTH_HEADER);
            height = heights.getHeader(HEIGHT_HEADER);
        } else {
            try {
                RasterSize rasterSize = readFileIntoDataAccess(source, heights);
                width = rasterSize.width;
                height = rasterSize.height;
                heights.setHeader(CACHE_VERSION_HEADER, CACHE_FORMAT_VERSION);
                heights.setHeader(WIDTH_HEADER, width);
                heights.setHeader(HEIGHT_HEADER, height);
                setLongHeader(heights, SOURCE_MODIFIED_HEADER, source.lastModified());
                setLongHeader(heights, SOURCE_LENGTH_HEADER, source.length());
                heights.flush();
            } catch (RuntimeException ex) {
                getDirectory().remove(cacheName);
                throw ex;
            }
        }

        HeightTile tile = new HeightTile(minLat, minLon, width, height, PRECISION, DEGREE, DEGREE);
        tile.setInterpolate(interpolate);
        tile.setHeights(heights);
        return tile;
    }

    private boolean matchesSource(DataAccess heights, File source) {
        int width = heights.getHeader(WIDTH_HEADER);
        int height = heights.getHeader(HEIGHT_HEADER);
        return heights.getHeader(CACHE_VERSION_HEADER) == CACHE_FORMAT_VERSION
                && width > 1
                && height > 1
                && heights.getCapacity() >= 2L * width * height
                && getLongHeader(heights, SOURCE_MODIFIED_HEADER) == source.lastModified()
                && getLongHeader(heights, SOURCE_LENGTH_HEADER) == source.length();
    }

    private RasterSize readFileIntoDataAccess(File source, DataAccess heights) {
        try (ImageInputStream input = ImageIO.createImageInputStream(source)) {
            if (input == null)
                throw new IllegalArgumentException("Cannot open elevation COG " + source);

            ImageReader reader = getTiffReader(input);
            try {
                reader.setInput(input, true, true);
                int width = reader.getWidth(0);
                int height = reader.getHeight(0);
                validateRasterSize(source, width, height);
                heights.create(2L * width * height);

                for (int y = 0; y < height; y += RASTER_CHUNK_HEIGHT) {
                    int chunkHeight = Math.min(RASTER_CHUNK_HEIGHT, height - y);
                    ImageReadParam readParam = reader.getDefaultReadParam();
                    readParam.setSourceRegion(new Rectangle(0, y, width, chunkHeight));
                    Raster raster = reader.readRaster(0, readParam);
                    if (raster.getNumBands() != 1)
                        throw new IllegalArgumentException("Elevation COG must contain exactly one band: " + source);
                    fillDataAccess(raster, heights, width, y);
                }
                return new RasterSize(width, height);
            } finally {
                reader.dispose();
            }
        } catch (IOException ex) {
            throw new RuntimeException("Cannot decode elevation COG " + source, ex);
        }
    }

    private ImageReader getTiffReader(ImageInputStream input) {
        Iterator<ImageReader> readers = ImageIO.getImageReaders(input);
        while (readers.hasNext()) {
            ImageReader reader = readers.next();
            if (reader.getClass().getName().startsWith(TWELVE_MONKEYS_READER_PREFIX))
                return reader;
            reader.dispose();
        }
        throw new IllegalStateException("No TIFF reader with floating-point Predictor 3 support is available");
    }

    private void validateRasterSize(File source, int width, int height) {
        if (width < 2 || height < 2)
            throw new IllegalArgumentException("Elevation COG must contain at least a 2x2 raster: " + source);
        if (width != height)
            throw new IllegalArgumentException("Elevation COG must use a square one-degree grid: " + source);
    }

    private void fillDataAccess(Raster raster, DataAccess heights, int width, int yOffset) {
        for (int y = 0; y < raster.getHeight(); y++) {
            for (int x = 0; x < width; x++) {
                double sample = raster.getSampleDouble(raster.getMinX() + x, raster.getMinY() + y, 0);
                short elevation = !Double.isFinite(sample) || sample < MIN_ELEVATION || sample > MAX_ELEVATION
                        ? Short.MIN_VALUE
                        : (short) Math.round(sample);
                heights.setShort(2L * ((long) (yOffset + y) * width + x), elevation);
            }
        }
    }

    private static class RasterSize {
        final int width;
        final int height;

        RasterSize(int width, int height) {
            this.width = width;
            this.height = height;
        }
    }

    static void setLongHeader(DataAccess heights, int bytePos, long value) {
        heights.setHeader(bytePos, (int) value);
        heights.setHeader(bytePos + 4, (int) (value >>> 32));
    }

    static long getLongHeader(DataAccess heights, int bytePos) {
        return ((long) heights.getHeader(bytePos + 4) << 32)
                | (heights.getHeader(bytePos) & 0xffffffffL);
    }

    String getFileName(double lat, double lon) {
        if (!isSupported(lat, lon))
            return null;

        int minLat = getMinLatitude(lat);
        int minLon = getMinLongitude(lon);
        return (minLat < 0 ? "s" : "n") + pad(Math.abs(minLat), 2)
                + (minLon < 0 ? "w" : "e") + pad(Math.abs(minLon), 3) + ".tif";
    }

    private boolean isSupported(double lat, double lon) {
        return Double.isFinite(lat) && Double.isFinite(lon)
                && lat >= MIN_LATITUDE && lat <= MAX_LATITUDE
                && lon >= MIN_LONGITUDE && lon <= MAX_LONGITUDE;
    }

    private int getMinLatitude(double lat) {
        return lat == MAX_LATITUDE ? MAX_LATITUDE - 1 : (int) Math.floor(lat);
    }

    private int getMinLongitude(double lon) {
        return lon == MAX_LONGITUDE ? MAX_LONGITUDE - 1 : (int) Math.floor(lon);
    }

    private String pad(int value, int width) {
        String result = Integer.toString(value);
        return "0".repeat(width - result.length()) + result;
    }

    @Override
    public void release() {
        synchronized (cacheData) {
            cacheData.clear();
            missingTiles.clear();
        }
        if (dir != null) {
            if (autoRemoveTemporary)
                dir.clear();
            else
                dir.close();
        }
    }

    @Override
    public String toString() {
        return "bikemap";
    }
}
