/*
 *  Licensed to GraphHopper GmbH under one or more contributor
 *  license agreements. See the NOTICE file distributed with this work for
 *  additional information regarding copyright ownership.
 *
 *  GraphHopper GmbH licenses this file to you under the Apache License,
 *  Version 2.0 (the "License"); you may not use this file except in
 *  compliance with the License. You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.graphhopper.reader.dem;

import com.graphhopper.storage.DataAccess;
import com.graphhopper.util.Downloader;
import software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.GetObjectRequest;
import software.amazon.awssdk.services.s3.model.NoSuchKeyException;

import javax.imageio.ImageIO;
import javax.imageio.ImageReadParam;
import javax.imageio.ImageReader;
import javax.imageio.stream.ImageInputStream;
import java.awt.Rectangle;
import java.awt.image.Raster;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.RandomAccessFile;
import java.net.HttpURLConnection;
import java.net.URI;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;

/**
 * Reads the one-degree Cloud Optimized GeoTIFFs generated by Bikemap's
 * {@code elevation_worker/commands/compute_continuous_tiles.py}.
 * <p>
 * The dataset uses lowercase SRTM-style names such as {@code n46e010.tif}, but unlike a regular
 * SRTM provider its tiles contain Float32 samples and can have different resolutions. The first
 * access to a tile converts its actual raster dimensions and values into GraphHopper's short-based
 * {@link DataAccess} format. The converted data is then memory-mapped by default.
 * <p>
 * The source can be a local {@code continuous} directory or a versioned S3/HTTP prefix set via
 * {@link #setBaseURL(String)}. Only converted caches are retained when using a remote source;
 * downloaded TIFFs are temporary. Valid caches can be read without the source being available.
 */
public class BikemapElevationProvider extends TileBasedElevationProvider {
    static final int MIN_LATITUDE = -60;
    static final int MAX_LATITUDE = 84;
    static final int MIN_LONGITUDE = -180;
    static final int MAX_LONGITUDE = 180;

    private static final int CACHE_FORMAT_VERSION = 2;
    private static final int CACHE_VERSION_HEADER = 4;
    private static final int WIDTH_HEADER = 8;
    private static final int HEIGHT_HEADER = 12;
    private static final int SOURCE_MODIFIED_HEADER = 16;
    private static final int SOURCE_LENGTH_HEADER = 24;
    private static final int SOURCE_ID_HEADER = 32;
    // DataAccess reserves 100 bytes before the raster's segment data.
    private static final int DATA_ACCESS_HEADER_BYTES = 100;
    private static final double PRECISION = 1e7;
    private static final int DEGREE = 1;
    private static final double MIN_ELEVATION = -1_000;
    private static final double MAX_ELEVATION = 12_000;
    private static final int RASTER_CHUNK_HEIGHT = 512;
    private static final String TWELVE_MONKEYS_READER_PREFIX = "com.twelvemonkeys.";

    private final Map<String, HeightTile> cacheData = new HashMap<>();
    private final Set<String> missingTiles = new HashSet<>();
    private S3Client s3Client;

    public BikemapElevationProvider() {
        this("");
    }

    public BikemapElevationProvider(String cacheDir) {
        super(cacheDir.isEmpty() ? "/tmp/bikemap" : cacheDir);
        baseUrl = getCacheDir().getAbsolutePath();
        downloader = new Downloader("GraphHopper BikemapReader");
    }

    @Override
    public BikemapElevationProvider setBaseURL(String baseUrl) {
        super.setBaseURL(baseUrl);
        if (isRemoteSource()) {
            URI uri = URI.create(baseUrl);
            if (uri.getHost() == null || uri.getUserInfo() != null || uri.getQuery() != null || uri.getFragment() != null
                    || ("s3".equals(uri.getScheme()) && uri.getPort() != -1))
                throw new IllegalArgumentException("Elevation base URL must be an S3/HTTP directory prefix");
            this.baseUrl = baseUrl.replaceAll("/+$", "");
        } else {
            if (baseUrl.contains("://"))
                throw new IllegalArgumentException("Unsupported elevation source: " + baseUrl);
            this.baseUrl = new File(baseUrl).getAbsoluteFile().toPath().normalize().toString();
        }
        return this;
    }

    private boolean isRemoteSource() {
        return baseUrl.startsWith("s3://") || baseUrl.startsWith("https://") || baseUrl.startsWith("http://");
    }

    @Override
    public double getEle(double lat, double lon) {
        String fileName = getFileName(lat, lon);
        if (fileName == null)
            return 0;

        HeightTile tile;
        synchronized (cacheData) {
            tile = cacheData.get(fileName);
            if (tile == null) {
                if (missingTiles.contains(fileName))
                    return 0;

                tile = loadTile(fileName, getMinLatitude(lat), getMinLongitude(lon));
                if (tile == null) {
                    missingTiles.add(fileName);
                    return 0;
                }
                cacheData.put(fileName, tile);
            }
        }
        return tile.getHeight(lat, lon);
    }

    private HeightTile loadTile(String fileName, int minLat, int minLon) {
        File source = isRemoteSource() ? null : new File(baseUrl, fileName);
        int[] sourceId = sourceId();
        String cacheName = "bikemap_" + fileName.substring(0, fileName.length() - 4) + ".gh";
        DataAccess heights = getDirectory().create(cacheName);
        boolean loadExisting = false;
        try {
            loadExisting = isCompleteCache(new File(getCacheDir(), cacheName)) && heights.loadExisting();
        } catch (Exception ex) {
            logger.warn("Cannot load {}, rebuilding it: {}", cacheName, ex.getMessage());
        }

        if (loadExisting && !isValidCache(heights, source, sourceId))
            loadExisting = false;

        if (!loadExisting) {
            // Also discard incomplete mappings after loadExisting failed or threw.
            getDirectory().remove(cacheName);
            heights = getDirectory().create(cacheName);
        }

        int width;
        int height;
        if (loadExisting) {
            width = heights.getHeader(WIDTH_HEADER);
            height = heights.getHeader(HEIGHT_HEADER);
        } else {
            Path temporarySource = null;
            try {
                if (isRemoteSource()) {
                    Files.createDirectories(getCacheDir().toPath());
                    temporarySource = Files.createTempFile(getCacheDir().toPath(), "bikemap-source-", ".tif");
                    if (!downloadSource(fileName, temporarySource)) {
                        getDirectory().remove(cacheName);
                        return null;
                    }
                    source = temporarySource.toFile();
                } else if (!source.isFile()) {
                    getDirectory().remove(cacheName);
                    return null;
                }
                Files.createDirectories(getCacheDir().toPath());
                RasterSize rasterSize = readFileIntoDataAccess(source, heights);
                width = rasterSize.width;
                height = rasterSize.height;
                heights.setHeader(CACHE_VERSION_HEADER, CACHE_FORMAT_VERSION);
                heights.setHeader(WIDTH_HEADER, width);
                heights.setHeader(HEIGHT_HEADER, height);
                setLongHeader(heights, SOURCE_MODIFIED_HEADER, source.lastModified());
                setLongHeader(heights, SOURCE_LENGTH_HEADER, source.length());
                for (int i = 0; i < sourceId.length; i++)
                    heights.setHeader(SOURCE_ID_HEADER + 4 * i, sourceId[i]);
                heights.flush();
            } catch (IOException ex) {
                getDirectory().remove(cacheName);
                throw new RuntimeException("Cannot fetch elevation COG " + fileName, ex);
            } catch (RuntimeException ex) {
                getDirectory().remove(cacheName);
                throw ex;
            } finally {
                if (temporarySource != null) {
                    try {
                        Files.deleteIfExists(temporarySource);
                    } catch (IOException ex) {
                        throw new RuntimeException("Cannot remove temporary elevation COG " + temporarySource, ex);
                    }
                }
            }
        }

        HeightTile tile = new HeightTile(minLat, minLon, width, height, PRECISION, DEGREE, DEGREE);
        tile.setInterpolate(interpolate);
        tile.setHeights(heights);
        return tile;
    }

    private boolean isCompleteCache(File cache) throws IOException {
        if (!cache.isFile())
            return false;
        // Check before loading: a writable memory mapping can silently extend a truncated file.
        try (RandomAccessFile input = new RandomAccessFile(cache, "r")) {
            if (!"GH".equals(input.readUTF()))
                return false;
            long dataLength = input.readLong() - DATA_ACCESS_HEADER_BYTES;
            int segmentSize = input.readInt();
            if (dataLength <= 0 || segmentSize < 128 || Integer.bitCount(segmentSize) != 1)
                return false;
            // MMAP stores the physical file length; RAM_STORE stores the capacity without the header.
            // Both yield the same segment count when rounded up (segments are at least 128 bytes).
            long segments = dataLength / segmentSize + (dataLength % segmentSize == 0 ? 0 : 1);
            return segments <= (Long.MAX_VALUE - DATA_ACCESS_HEADER_BYTES) / segmentSize
                    && input.length() == DATA_ACCESS_HEADER_BYTES + segments * segmentSize;
        }
    }

    private boolean isValidCache(DataAccess heights, File source, int[] sourceId) {
        int width = heights.getHeader(WIDTH_HEADER);
        int height = heights.getHeader(HEIGHT_HEADER);
        if (width < 2 || width != height || heights.getCapacity() < 2L * width * height)
            return false;

        int version = heights.getHeader(CACHE_VERSION_HEADER);
        if (version == 1) {
            // Existing sidecars had no source namespace and were always built beside local TIFFs.
            if (isRemoteSource() || !baseUrl.equals(getCacheDir().getAbsolutePath()))
                return false;
        } else if (version == CACHE_FORMAT_VERSION) {
            for (int i = 0; i < sourceId.length; i++)
                if (heights.getHeader(SOURCE_ID_HEADER + 4 * i) != sourceId[i])
                    return false;
        } else {
            return false;
        }

        return source == null || !source.isFile()
                || (getLongHeader(heights, SOURCE_MODIFIED_HEADER) == source.lastModified()
                && getLongHeader(heights, SOURCE_LENGTH_HEADER) == source.length());
    }

    private int[] sourceId() {
        try {
            ByteBuffer digest = ByteBuffer.wrap(MessageDigest.getInstance("SHA-256")
                    .digest(baseUrl.getBytes(StandardCharsets.UTF_8)));
            int[] id = new int[8];
            for (int i = 0; i < id.length; i++)
                id[i] = digest.getInt();
            return id;
        } catch (NoSuchAlgorithmException ex) {
            throw new IllegalStateException(ex);
        }
    }

    private boolean downloadSource(String fileName, Path target) throws IOException {
        if (baseUrl.startsWith("s3://")) {
            URI uri = URI.create(baseUrl + "/" + fileName);
            if (s3Client == null)
                s3Client = createS3Client();
            GetObjectRequest request = GetObjectRequest.builder()
                    .bucket(uri.getHost()).key(uri.getPath().substring(1)).build();
            try (InputStream input = s3Client.getObject(request)) {
                Files.copy(input, target, StandardCopyOption.REPLACE_EXISTING);
            } catch (NoSuchKeyException ex) {
                return false;
            }
        } else {
            HttpURLConnection connection = downloader.createConnection(baseUrl + "/" + fileName);
            try {
                if (connection.getResponseCode() == HttpURLConnection.HTTP_NOT_FOUND)
                    return false;
                try (InputStream input = downloader.fetch(connection, false)) {
                    Files.copy(input, target, StandardCopyOption.REPLACE_EXISTING);
                }
            } finally {
                connection.disconnect();
            }
        }
        return true;
    }

    S3Client createS3Client() {
        return S3Client.builder().httpClientBuilder(UrlConnectionHttpClient.builder()).build();
    }

    private RasterSize readFileIntoDataAccess(File source, DataAccess heights) {
        try (ImageInputStream input = ImageIO.createImageInputStream(source)) {
            if (input == null)
                throw new IllegalArgumentException("Cannot open elevation COG " + source);

            ImageReader reader = getTiffReader(input);
            try {
                reader.setInput(input, true, true);
                int width = reader.getWidth(0);
                int height = reader.getHeight(0);
                validateRasterSize(source, width, height);
                heights.create(2L * width * height);

                for (int y = 0; y < height; y += RASTER_CHUNK_HEIGHT) {
                    int chunkHeight = Math.min(RASTER_CHUNK_HEIGHT, height - y);
                    ImageReadParam readParam = reader.getDefaultReadParam();
                    readParam.setSourceRegion(new Rectangle(0, y, width, chunkHeight));
                    Raster raster = reader.readRaster(0, readParam);
                    if (raster.getNumBands() != 1)
                        throw new IllegalArgumentException("Elevation COG must contain exactly one band: " + source);
                    fillDataAccess(raster, heights, width, y);
                }
                return new RasterSize(width, height);
            } finally {
                reader.dispose();
            }
        } catch (IOException ex) {
            throw new RuntimeException("Cannot decode elevation COG " + source, ex);
        }
    }

    private ImageReader getTiffReader(ImageInputStream input) {
        Iterator<ImageReader> readers = ImageIO.getImageReaders(input);
        while (readers.hasNext()) {
            ImageReader reader = readers.next();
            if (reader.getClass().getName().startsWith(TWELVE_MONKEYS_READER_PREFIX))
                return reader;
            reader.dispose();
        }
        throw new IllegalStateException("No TIFF reader with floating-point Predictor 3 support is available");
    }

    private void validateRasterSize(File source, int width, int height) {
        if (width < 2 || height < 2)
            throw new IllegalArgumentException("Elevation COG must contain at least a 2x2 raster: " + source);
        if (width != height)
            throw new IllegalArgumentException("Elevation COG must use a square one-degree grid: " + source);
    }

    private void fillDataAccess(Raster raster, DataAccess heights, int width, int yOffset) {
        for (int y = 0; y < raster.getHeight(); y++) {
            for (int x = 0; x < width; x++) {
                double sample = raster.getSampleDouble(raster.getMinX() + x, raster.getMinY() + y, 0);
                short elevation = !Double.isFinite(sample) || sample < MIN_ELEVATION || sample > MAX_ELEVATION
                        ? Short.MIN_VALUE
                        : (short) Math.round(sample);
                heights.setShort(2L * ((long) (yOffset + y) * width + x), elevation);
            }
        }
    }

    private static class RasterSize {
        final int width;
        final int height;

        RasterSize(int width, int height) {
            this.width = width;
            this.height = height;
        }
    }

    static void setLongHeader(DataAccess heights, int bytePos, long value) {
        heights.setHeader(bytePos, (int) value);
        heights.setHeader(bytePos + 4, (int) (value >>> 32));
    }

    static long getLongHeader(DataAccess heights, int bytePos) {
        return ((long) heights.getHeader(bytePos + 4) << 32)
                | (heights.getHeader(bytePos) & 0xffffffffL);
    }

    String getFileName(double lat, double lon) {
        if (!isSupported(lat, lon))
            return null;

        int minLat = getMinLatitude(lat);
        int minLon = getMinLongitude(lon);
        return (minLat < 0 ? "s" : "n") + pad(Math.abs(minLat), 2)
                + (minLon < 0 ? "w" : "e") + pad(Math.abs(minLon), 3) + ".tif";
    }

    private boolean isSupported(double lat, double lon) {
        return Double.isFinite(lat) && Double.isFinite(lon)
                && lat >= MIN_LATITUDE && lat <= MAX_LATITUDE
                && lon >= MIN_LONGITUDE && lon <= MAX_LONGITUDE;
    }

    private int getMinLatitude(double lat) {
        return lat == MAX_LATITUDE ? MAX_LATITUDE - 1 : (int) Math.floor(lat);
    }

    private int getMinLongitude(double lon) {
        return lon == MAX_LONGITUDE ? MAX_LONGITUDE - 1 : (int) Math.floor(lon);
    }

    private String pad(int value, int width) {
        String result = Integer.toString(value);
        return "0".repeat(width - result.length()) + result;
    }

    @Override
    public void release() {
        synchronized (cacheData) {
            cacheData.clear();
            missingTiles.clear();
        }
        if (dir != null) {
            if (autoRemoveTemporary)
                dir.clear();
            else
                dir.close();
            dir = null;
        }
        if (s3Client != null) {
            s3Client.close();
            s3Client = null;
        }
    }

    @Override
    public String toString() {
        return "bikemap";
    }
}
